# Generated by Django 4.0.4 on 2022-07-24 18:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=54)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(choices=[('مكة المكرمة', 'مكة المكرمة'), ('الرياض', 'الرياض'), ('الشرقية', 'الشرقية'), ('عسير', 'عسير'), ('المدينة المنورة', 'المدينة المنورة'), ('جازان', 'جازان'), ('القصيم', 'القصيم'), ('تبوك', 'تبوك'), ('حائل', 'حائل'), ('نجران', 'نجران'), ('الجوف', 'الجوف'), ('الباحة', 'الباحة'), ('الحدود الشمالية', 'الحدود الشمالية')], max_length=64)),
                ('type', models.CharField(choices=[('نعناع', 'نعناع'), ('نخيل', 'نخيل')], max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(blank=True, max_length=1024)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
