# Generated by Django 4.0.6 on 2022-07-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsApp', '0005_alter_post_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('نخيل', 'نخيل'), ('شجرة النيم', 'شجرة النيم'), ('شجرة الفيكس الامريكي', 'شجرة الفيكس الامريكي'), ('شجرة الخبيز الساحلي ', 'شجرة الخبيز الساحلي '), ('شجرة اللبخ', 'شجرة اللبخ'), ('شجرة الفيكس النقالي', 'شجرة الفيكس النقالي'), ('شجرة فرشاة الزجاج', 'شجرة فرشاة الزجاج'), ('ورود صغيره', 'ورود صغيره'), ('شجرة عادية ', 'شجرة عادية ')], max_length=64),
        ),
    ]
