# Generated by Django 4.0.6 on 2022-07-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, max_length=1024)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('pointe', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
