# Generated by Django 4.0.4 on 2022-07-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='pointe',
            new_name='points',
        ),
    ]
