# Generated by Django 4.0.6 on 2022-07-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0002_rename_pointe_coupons_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
