# Generated by Django 4.0.4 on 2022-07-24 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
