# Generated by Django 4.0.4 on 2022-07-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
    ]
