# Generated by Django 4.0.6 on 2022-07-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totalScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='usedScore',
            field=models.IntegerField(default=0),
        ),
    ]
