# Generated by Django 4.0.6 on 2022-07-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avtar',
            field=models.URLField(default='https://cdn5.vectorstock.com/i/1000x1000/50/29/user-icon-male-person-symbol-profile-avatar-vector-20715029.jpg', max_length=1024),
        ),
    ]
