# Generated by Django 4.0.4 on 2022-07-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PostsApp', '0002_remove_post_rating_post_is_rated'),
        ('RatingsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AlterField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostsApp.post'),
        ),
    ]
